---

# php.ini settings
php_memory_limit: 512M
php_max_execution_time: 60
php_max_input_time: 60
php_max_input_vars: 2000
php_post_max_size: 100M
php_upload_max_filesize: 100M
php_display_errors: On
php_display_startup_errors: On
php_html_errors: On
php_date_timezone: Europe/Madrid
php_mbstring_http_input: pass
php_mbstring_http_output: pass

# Install PECL uploadprogress
php_pecl_uploadprogress: false
