---

# Install and configure MailHog.
- name: Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  become: yes

- name: Download MailHog binary.
  get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Copy mailhog init script into place.
  template:
    src: mailhog.init.j2
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Copy mailhog systemd unit file into place (for systemd systems).
  template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755

- name: Ensure mailhog is enabled and will start on boot.
  service: name=mailhog state=restarted enabled=yes
  become: yes

# Install and configure sSMTP.
- import_tasks: setup.yml
  when: mailhog_install_ssmtp
  become: yes

- name: Copy sSMTP configuration.
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  when: mailhog_install_ssmtp
