---
- name: Download daemonize archive.
  get_url:
    url: "https://github.com/bmc/daemonize/archive/release-{{ daemonize_version }}.tar.gz"
    dest: "{{ workspace }}/daemonize-{{ daemonize_version }}.tar.gz"
  become: yes
  
- name: Expand daemonize archive.
  command: >
    tar -zxf {{ workspace }}/daemonize-{{ daemonize_version }}.tar.gz
    chdir={{ workspace }}
    creates={{ workspace }}/daemonize-release-{{ daemonize_version }}/INSTALL
  become: yes

- name: Check if daemonize is installed.
  command: which daemonize
  changed_when: false
  failed_when: false
  register: daemonize_installed
  become: yes

- name: Build daemonize.
  command: >
    {{ item }}
    chdir={{ workspace }}/daemonize-release-{{ daemonize_version }}
  when: daemonize_installed|failed
  with_items:
    - ./configure
    - "make prefix={{ daemonize_install_path }}"
    - "make prefix={{ daemonize_install_path }} install"
  become: yes
